### ISSUE TITLE
Extensions are deleted during unyson update

### ISSUE THREAD

**Issue by GheorgheP** [ThemeFuse/Unyson-CLI#2]
When executing the  `wp unyson update`, `wp unyson upgrade`, `wp unyson downgrade` commands, the extensions are removed entirely.

**Comment by andreiglingeanu** [comment]
That is because you are not doing it properly -- you use [WordPress plugins API](https://github.com/ThemeFuse/Unyson-CLI/blob/master/src/Commands/Unyson.php#L290-L298) when you don't really need that because unyson is already installed.

The proper way to do that and this method correctly preserves already install extensions is listed [here](https://github.com/ThemeFuse/Unyson-CLI/blob/master/src/Commands/Unyson.php#L290-L298). The only problem with that method is that it is coupled to the `wp-admin` HTTP flow, which we should get rid of and rely only on `WP_Error` for managing state.

Ideally, the implementation should work fine even if Unyson is deactived. Which means we should manually `require` a specific file from `unyson` (as a plugin) which has that logic.

In my view, CLI should be a transparent and very simple shell to the whole Unyson codebase. And unyson codebase will only benefit from that.

**Comment by GheorgheP** [comment]
I think if WordPress has already a built in method, we should use and not build our bicycles, as this will be already our responsibility to handle all problems.

My idea is to save all extensions before updating the plugin, then restore them.

**Comment by andreiglingeanu** [comment]
> My idea is to save all extensions before updating the plugin, then restore them.

This is exactly what Unyson already [have](https://github.com/ThemeFuse/Unyson/blob/v2.6.16/framework/extensions/update/class-fw-extension-update.php#L309-L319). This logic is already implemented and it runs when you update Unyson from WordPress UI.

Check `$merge_extensions` parameter.
